Create contributing.md
se701-group6/A2 pull request #31
Opened 2020-03-11 05:28 UTC by skmu104

closes #6

2020-03-11 05:34 UTC, misl000 commented on docs/contributing.md
> + see below for links and information related to your intended contributions
```suggestion
 See below for links and information related to your intended contributions
```

2020-03-11 05:43 UTC, jwar663 approved these changes
Looks good to me!
Is this supposed to be solving issue #3 though?

2020-03-11 07:59 UTC, dder725 approved these changes
Looks awesome @skmu104 !

2020-03-11 08:23 UTC, williamlixu requested changes
Would you please just rename the file CONTRIBUTING.md and also move out from a docs folder into the root directory so it's consistent.
Looks good apart from that :)

2020-03-11 08:23 UTC, williamlixu commented on docs/contributing.md
> +## other useful links
```suggestion
## Other useful links
```

2020-03-11 08:38 UTC, williamlixu commented on docs/contributing.md
> +- ###  [Bug reporting](https://github.com/SOFTENG701G1/A1/wiki/Bug-Reporting)
Save yourself some work and just remove the bug reporting page, issues can cover bugs :)

2020-03-12 06:52 UTC, williamlixu approved these changes
LGTM! Thanks for fixing it!

2020-03-12 06:53 UTC, merged