Created login page
se701-group6/A2 pull request #55
Opened 2020-03-14 22:25 UTC by babe269

Closes #44 

**Description**

Added the basic screen based design of the mock up login page. Integrated with the routing of other pages within the application.

No new files were added but the login page was modified with the new content.

**Testing**

Ran and functional.

**Checklist**

- [*] I have tested my change
- [*] Code builds successfully and all tests pass
- [*] Docs have been added/updated if needed

2020-03-14 22:44 UTC, tgre605 approved these changes
Looks good

2020-03-14 23:27 UTC, tgre605 submitted a review, later dismissed
Looks good to me

2020-03-14 23:32 UTC, williamlixu requested changes
LGTM, just small fix to move CSS files. Also the existing CSS is in PascalCase, so would be good to match it :)

2020-03-14 23:32 UTC, williamlixu commented on split-webapp/split/src/pages/Login.js
> +    outterContainer: {
This should be moved to the CSS file

2020-03-15 00:48 UTC, tgre605 approved these changes
Looks good

2020-03-15 04:23 UTC, williamlixu requested changes
Looks like there's a merge conflict in the CSS file now

2020-03-15 04:23 UTC, williamlixu commented on split-webapp/split/src/App.css
> +/* .TextField {
Clean up this CSS please :)

2020-03-15 05:24 UTC, williamlixu approved these changes
LGTM

2020-03-15 05:28 UTC, williamlixu commented
Also closes #40, but logo still needs to be added elsewhere (only on home/login pages currently).

2020-03-15 05:45 UTC, merged