Initial README template
se701-group6/A2 pull request #69
Opened 2020-03-15 23:44 UTC by skmu104

Closes #(issue)

**Description**

Created a template for the README. Some information still needed to be filled out, hopefully by product team and developers

**Testing**

Describe testing that has been done

**Checklist**

- [ x ] Docs have been added/updated if needed

2020-03-16 00:00 UTC, dder725 requested changes

2020-03-16 00:00 UTC, dder725 commented on README.md
> +# SPLit
I have asked the design team to add a logo to our docs. Would be good to plug it into the README for an extra fresh look of our repo. Will update you once it is done :) Otherwise, everything looks great!

2020-03-16 04:41 UTC, SeanSpires commented
Looks great.

2020-03-16 04:41 UTC, SeanSpires approved these changes

2020-03-16 04:43 UTC, SeanSpires requested changes
Should we have a brief project description section in the README? If so, can you add in this section?

2020-03-16 05:27 UTC, skmu104 commented
> Should we have a brief project description section in the README? If so, can you add in this section?
@SeanSpires I saw the separate issue you created and assigned to Devashish so I thought he could add it in after the changes go through

2020-03-16 05:32 UTC, williamlixu requested changes
Make sure to put the issue number in the description! I'm happy to fill out some of the dev details when this is in.

2020-03-16 05:32 UTC, williamlixu commented on README.md
> +# Aknowledgements
nit: spelling

2020-03-16 08:16 UTC, dder725 commented on README.md
> +# SPLit
@skmu104 the logo can be found at the bottom of [this](https://github.com/SOFTENG701G1/A1/wiki/HiFi-Prototypes) page

2020-03-17 00:20 UTC, misl000 commented
Looks pretty good! Just wondering if the image is a bit large thou?

2020-03-17 00:22 UTC, williamlixu approved these changes
LGTM, nice work.

2020-03-17 01:26 UTC, dder725 approved these changes
Looks good to me, awesome work :)

2020-03-17 04:06 UTC, SeanSpires approved these changes

2020-03-17 04:18 UTC, merged